### ISSUE TITLE
Tracking Features (Work in Progress)

### ISSUE THREAD

**Issue by avionmission** [avionmission/OpenShop#1]
### Features List
- [x] Setting up react-navigation
- [x] Sign up and Sign in screen with tabs
- [x] Home page Desing
- [x] A carousel widget for displaying ads and other content.
- [ ] Search functionality in DiscoverScreen.js
- [ ] Building a Product Details Screen.
- [ ] Setting up redux
- [ ] Building Cart feature.
- [ ] Building Wishlist feature.
- [ ] Setting up Firebase for authentication

**Comment by avionmission** [comment]
```[task list]
- [ ] Setting up react-navigation
- [ ] Signup and Signin screen with tabs
- [ ] Home page Desing
- [ ] A carousel widget for displaying ads and other content.
- [ ] Search functionality in DiscoverScreen.js
- [ ] Building a Product Details Screen.
- [ ] Setting up redux
- [ ] Building Cart feature.
- [ ] Building Wishlist feature.
- [ ] Setting up Firebase for authentication 
```

**Comment by avionmission** [comment]
### Features List
- [ ] Setting up react-navigation
- [ ] Sign up and Sign in screen with tabs
- [ ] Home page Desing
- [ ] A carousel widget for displaying ads and other content.
- [ ] Search functionality in DiscoverScreen.js
- [ ] Building a Product Details Screen.
- [ ] Setting up redux
- [ ] Building Cart feature.
- [ ] Building Wishlist feature.
- [ ] Setting up Firebase for authentication
